### ISSUE TITLE
Incident on 2020-11-27 16:04 UTC: degraded availability for GitHub Actions

### ISSUE THREAD

**Issue by socheatsok78** [soramitsukhmer/ideas#4]
GitHub Action is currently having issues pulling repository to run the workflow https://github.com/actions/checkout/issues/394

**Comment by socheatsok78** [comment]
All of our services is affected! Please be patient!

@phyrumsk, @sovannarithcheav, @phuylai-oeung, @VandyTheCoder

**Comment by VandyTheCoder** [comment]
Noted, bong.

**Comment by socheatsok78** [comment]
Incident on 2020-11-27 16:04 UTC  https://www.githubstatus.com/incidents/vts24q167tc8?utm_ts=1606493055

**Comment by socheatsok78** [comment]
Everything is up and running!
